### ISSUE TITLE
Alpaca 8.1.0 not starting on Linux Mint

### ISSUE THREAD

**Issue by BoFFire** [Jeffser/Alpaca#993]
Hi,

Alpaca 8.1.0 via Flathub was not starting on my Linux Mint.

I run :

```
flatpak run --command=sh com.jeffser.Alpaca

python -m pip install --user --force-reinstall --upgrade six
Collecting six
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six
Successfully installed six-1.17.0

exit

flatpak run com.jeffser.Alpaca
```

And it is working again.

**Comment by linuxkernel94** [comment]
Same error here on Fedora

**Comment by usernamefoo** [comment]
I had to run `python -m ensurepip --default-pip` first becuase pip was not installed.
Then the reinstall of the six modules fixed the problem for me.

**Comment by mvanthoor** [comment]
@BoFFire @usernamefoo :

This fixed it, thanks.

I assume that it'd be fastest to just remove and install Alpaca if this change creates problems with future updates.

**Comment by Jeffser** [comment]
I just added `six` to the flathub manifest, basically what happen is, six had an outdated version, should be fixed now

**Comment by linuxkernel94** [comment]
Hi, I just updated and the error persists, even if I delete the whole configuration folder: 

```
Traceback (most recent call last):
  File "/app/bin/alpaca", line 46, in <module>
    from alpaca import main
  File "/app/share/Alpaca/alpaca/main.py", line 34, in <module>
    from .widgets import activities
  File "/app/share/Alpaca/alpaca/widgets/__init__.py", line 3, in <module>
    from . import chat, dialog, message, attachments, voice, instances, models, welcome, preferences, activities
  File "/app/share/Alpaca/alpaca/widgets/chat.py", line 11, in <module>
    from . import dialog, voice
  File "/app/share/Alpaca/alpaca/widgets/voice.py", line 11, in <module>
    from . import dialog, models, blocks, activities
  File "/app/share/Alpaca/alpaca/widgets/models/__init__.py", line 3, in <module>
    from . import added, available, pulling, common, speech, creator, image
  File "/app/share/Alpaca/alpaca/widgets/models/added.py", line 7, in <module>
    from .. import dialog, attachments
  File "/app/share/Alpaca/alpaca/widgets/attachments.py", line 19, in <module>
    from . import blocks, dialog, voice, activities
  File "/app/share/Alpaca/alpaca/widgets/blocks/__init__.py", line 5, in <module>
    from .latex import LatexRenderer
  File "/app/share/Alpaca/alpaca/widgets/blocks/latex.py", line 10, in <module>
    from matplotlib.figure import Figure
  File "/app/lib/python3.13/site-packages/matplotlib/figure.py", line 40, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "/app/lib/python3.13/site-packages/matplotlib/projections/__init__.py", line 55, in <module>
    from .. import axes, _docstring
  File "/app/lib/python3.13/site-packages/matplotlib/axes/__init__.py", line 2, in <module>
    from ._axes import Axes
  File "/app/lib/python3.13/site-packages/matplotlib/axes/_axes.py", line 11, in <module>
    import matplotlib.category  # Register category unit converter as side effect.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.13/site-packages/matplotlib/category.py", line 14, in <module>
    import dateutil.parser
  File "/app/lib/python3.13/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/app/lib/python3.13/site-packages/dateutil/parser/_parser.py", line 50, in <module>
    from .. import tz
  File "/app/lib/python3.13/site-packages/dateutil/__init__.py", line 16, in __getattr__
    return importlib.import_module("." + name, __name__)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.13/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/app/lib/python3.13/site-packages/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
ModuleNotFoundError: No module named 'six.moves'

```

**Comment by sbe-arg** [comment]
Issue continues after 8.1.1

**Comment by Jeffser** [comment]
Please wait for the update

**Comment by linuxkernel94** [comment]
Fixed! 😍
